version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: snapcloset-db
    environment:
      POSTGRES_DB: snapcloset
      POSTGRES_USER: snapcloset_user
      POSTGRES_PASSWORD: snapcloset_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
